=== Thaer455/Betrieb/src/main/resources/xml/Mitarbeiter.dtd
<!ELEMENT Mitarbeiterliste (Mitarbeiter*)>
        <!ATTLIST Mitarbeiterliste version CDATA #REQUIRED>

        <!ELEMENT Mitarbeiter (Mitarbeiternummer, Vorname, Nachname, Strasse, PLZ, Ort, Telefon, Email)>
        <!ELEMENT Mitarbeiternummer (#PCDATA)>
        <!ELEMENT Vorname (#PCDATA)>
        <!ELEMENT Nachname (#PCDATA)>
        <!ELEMENT Strasse (#PCDATA)>
        <!ELEMENT PLZ (#PCDATA)>
        <!ELEMENT Ort (#PCDATA)>
        <!ELEMENT Telefon (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>

=== Thaer455/Betrieb/src/main/resources/xml/Mitarbeiter.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Mitarbeiterliste SYSTEM "Mitarbeiter.dtd">
<Mitarbeiterliste>
	<Mitarbeiter>
		<Mitarbeiternummer>3241</Mitarbeiternummer>
		<Vorname>Gordon</Vorname>
		<Nachname>Bray</Nachname>
		<Strasse>73277 Figueroa Islands</Strasse>
		<PLZ>94974</PLZ>
		<Ort>New John</Ort>
		<Telefon>+1-979-148-40152</Telefon>
		<Email>kelly.george@jones-martin.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>1246</Mitarbeiternummer>
		<Vorname>Lauren</Vorname>
		<Nachname>Lane</Nachname>
		<Strasse>659 King Cape Suite 804</Strasse>
		<PLZ>36633</PLZ>
		<Ort>Port Anna</Ort>
		<Telefon>+1-979-158-40152</Telefon>
		<Email>lauren.lane@hotmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>2711</Mitarbeiternummer>
		<Vorname>Shelby</Vorname>
		<Nachname>Wallace</Nachname>
		<Strasse>924 Joseph Wall</Strasse>
		<PLZ>58405</PLZ>
		<Ort>West Jacqueline</Ort>
		<Telefon>+1-979-184-80152</Telefon>
		<Email>shelby.wallace@hotmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>4669</Mitarbeiternummer>
		<Vorname>Candace</Vorname>
		<Nachname>Jarvis</Nachname>
		<Strasse>0241 Day Orchard</Strasse>
		<PLZ>34648</PLZ>
		<Ort>South Nicole</Ort>
		<Telefon>+1-154-752-7024</Telefon>
		<Email>candace.jarvis@yahoo.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>4182</Mitarbeiternummer>
		<Vorname>Richard</Vorname>
		<Nachname>Campbell</Nachname>
		<Strasse>08090 Steven Curve Suite 101</Strasse>
		<PLZ>81331</PLZ>
		<Ort>Suzanneport</Ort>
		<Telefon>+1-421-727-7673</Telefon>
		<Email>richard.campbell@gmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>4964</Mitarbeiternummer>
		<Vorname>Hailey</Vorname>
		<Nachname>Nguyen</Nachname>
		<Strasse>09158 Alexandria Glen</Strasse>
		<PLZ>07861</PLZ>
		<Ort>South Drew</Ort>
		<Telefon>+1-420-672-1990x207</Telefon>
		<Email>hailey.nguyen@murphy.biz</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>6505</Mitarbeiternummer>
		<Vorname>Bradley</Vorname>
		<Nachname>Frederick</Nachname>
		<Strasse>51316 Gallagher Locks</Strasse>
		<PLZ>07224</PLZ>
		<Ort>New Stephenport</Ort>
		<Telefon>+1-937-650-0669</Telefon>
		<Email>bradley.frederick@hotmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>3285</Mitarbeiternummer>
		<Vorname>Alvin</Vorname>
		<Nachname>Neal</Nachname>
		<Strasse>7997 James Courts Apt. 572</Strasse>
		<PLZ>43766</PLZ>
		<Ort>New Jeremymouth</Ort>
		<Telefon>+1-484-627-6073</Telefon>
		<Email>alvin.neal@zamora.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>7688</Mitarbeiternummer>
		<Vorname>Sara</Vorname>
		<Nachname>Mckinney</Nachname>
		<Strasse>5881 Hatfield Squares</Strasse>
		<PLZ>84372</PLZ>
		<Ort>Bakerview</Ort>
		<Telefon>+1-122-829-4901</Telefon>
		<Email>sara.mckinney@larson-myers.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>7154</Mitarbeiternummer>
		<Vorname>Chad</Vorname>
		<Nachname>Pacheco</Nachname>
		<Strasse>0093 Stephanie Vista</Strasse>
		<PLZ>91861</PLZ>
		<Ort>Hudsonborough</Ort>
		<Telefon>+1-878-529-7762</Telefon>
		<Email>chad.pacheco@logan-baker.biz</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>6725</Mitarbeiternummer>
		<Vorname>Lucas</Vorname>
		<Nachname>Reyes</Nachname>
		<Strasse>65785 Zavala Hill</Strasse>
		<PLZ>14137</PLZ>
		<Ort>Samuelhaven</Ort>
		<Telefon>+1-395-090-5227</Telefon>
		<Email>lucas.reyes@gmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>4754</Mitarbeiternummer>
		<Vorname>Mallory</Vorname>
		<Nachname>Lyons</Nachname>
		<Strasse>784 Erica View</Strasse>
		<PLZ>11239</PLZ>
		<Ort>Millschester</Ort>
		<Telefon>+1-979-184-0152</Telefon>
		<Email>mallory.lyons@bailey.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>8703</Mitarbeiternummer>
		<Vorname>Joseph</Vorname>
		<Nachname>Lyons</Nachname>
		<Strasse>83166 Casey Mountains</Strasse>
		<PLZ>11494</PLZ>
		<Ort>Sanchezhaven</Ort>
		<Telefon>+1-975-918-40152</Telefon>
		<Email>joseph.lyons@gmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>9313</Mitarbeiternummer>
		<Vorname>Linda</Vorname>
		<Nachname>Weaver</Nachname>
		<Strasse>6131 Gonzalez Springs Apt. 412</Strasse>
		<PLZ>60079</PLZ>
		<Ort>Dukebury</Ort>
		<Telefon>+1-503-381-0552x476</Telefon>
		<Email>linda.weaver@gmail.com</Email>
	</Mitarbeiter>
	<Mitarbeiter>
		<Mitarbeiternummer>1014</Mitarbeiternummer>
		<Vorname>Amy</Vorname>
		<Nachname>Sanchez</Nachname>
		<Strasse>980 Quinn Ways</Strasse>
		<PLZ>86374</PLZ>
		<Ort>Port Antonioland</Ort>
		<Telefon>+1-979-148-40152</Telefon>
		<Email>amy.sanchez@hotmail.com</Email>
	</Mitarbeiter>
</Mitarbeiterliste>
